SPO-5857 Авторизация и Профиль
ivatar39/board_manager pull request #1
Opened 2021-06-11 15:05 UTC by ivatar39

Имплементирован базовый флоу: 
1. Ввод ФИО.
2. Проверка на то, есть ли юзер с таким именем или нет.
3. Если нет, то создаётся новый. Если есть, то вход по старым данным.
4. Просмотр информации в профиле
5. Выход из аккаунта, смена параметра "isAuthorized" на "false".

2021-06-15 07:42 UTC, saturov requested changes

2021-06-15 07:42 UTC, saturov commented on .gitignore
> +lib/tools
А почему было решено инструменты не коммитить?

2021-06-15 07:42 UTC, saturov commented on pubspec.yaml
> +  auto_route: 2.2.0
Почему навигацию было решено делать через это? Каких возможностей в стандартном подходе не хватило?

2021-06-15 07:42 UTC, saturov commented on pubspec.yaml
> +  hive: ^2.0.4
Рассматривал ли ты другие варианты для персистентного хранения данных? Почему остановился на этом?

2021-06-15 07:42 UTC, saturov commented on lib/ui/splash/splash_wm.dart
> +  }
В таких функциях как onLoad(), да и в других переопределенных функциях, которые можно назвать функциями жизненного цикла WM, лучше не писать код непосредственно, а лишь осуществлять вызовы других функций. Так код бегло читать станет намного проще.

Вынеси всё это в одну функцию с названием, отражающим суть происходящего.

2021-06-15 07:42 UTC, saturov commented on lib/ui/splash/splash_wm.dart
> +  final AuthRepository _repository;
Не выразительное имя. Добавится сюда какой-нибудь другой репозиторий, что делать тогда? Трогать код, который не относится к делу?

2021-06-15 07:42 UTC, saturov commented on lib/ui/splash/splash_page.dart
> +class SplashPage extends CoreMwwmWidget<SplashWidgetModel> {
Мы называем экраны не страницами, а всё же экранами обычно. Поэтому не Page, а Screen.

2021-06-15 07:42 UTC, saturov commented on lib/ui/splash/splash_page.dart
> +class SplashPage extends CoreMwwmWidget<SplashWidgetModel> {
Мы называем экраны не страницами, а всё же экранами обычно. Поэтому не Page, а Screen.

2021-06-15 07:42 UTC, saturov commented on lib/ui/splash/splash_page.dart
> +          ),
Обычно, мы выносим создание WM в top-level функцию. Тем самым, хотя бы визуально отделяя DI от WM.

2021-06-15 07:42 UTC, saturov commented on lib/ui/router/app_router.dart
> +)
Расскажи мне про пакет auto_route подробнее. Я им никогда не пользовался. Что он умеет хорошего?

2021-06-15 07:42 UTC, saturov commented on lib/ui/profile/profile_wm.dart
> +  final AuthRepository _repository;
Поработать над именованием поля класса. Сейчас оно ни о чем не говорит.

2021-06-15 07:42 UTC, saturov commented on lib/ui/profile/profile_wm.dart
> +  }
Функции не стоит переопределять, если это не имеет понятного смысла. 
Код "на будущее" складировать в репозитории тоже не нужно. Это верный способ превратить кодовую базу в бардак.

2021-06-15 07:42 UTC, saturov commented on lib/ui/profile/profile_wm.dart
> +  }
Наименование функции не в полной мере соответствует тому, что происходит в её реализации.

2021-06-15 07:42 UTC, saturov commented on lib/ui/profile/profile_page.dart
> +class ProfilePage extends CoreMwwmWidget<ProfileWidgetModel> {
Page -> Screen

2021-06-15 07:42 UTC, saturov commented on lib/ui/profile/profile_page.dart
> +          ),
Вынести создание WM в top-level функцию.

2021-06-15 07:42 UTC, saturov commented on lib/ui/profile/profile_page.dart
> +      createWidgetState() {
Странный перенос.

2021-06-15 07:42 UTC, saturov commented on lib/ui/profile/profile_page.dart
> +        title: const Text('Профиль'),
На будущее - в любой проект сразу закладывай механизм локализации для строк. Задним числом будет очень сложно интегрировать.

2021-06-15 07:42 UTC, saturov commented on lib/ui/auth/auth_wm.dart
> +  final AuthRepository _repository;
Поправить именование

2021-06-15 07:42 UTC, saturov commented on lib/ui/auth/auth_wm.dart
> +  }
Не переопределять функцию без реализации

2021-06-15 07:42 UTC, saturov commented on lib/ui/auth/auth_wm.dart
> +    } else {}
Не оставлять пустых логических веток.

2021-06-15 07:42 UTC, saturov commented on lib/ui/auth/auth_wm.dart
> +  Future<void> signIn(String name) async {
Привести наименование функции в соответствие с её реальной ответственностью.

2021-06-15 07:42 UTC, saturov commented on lib/ui/app/app.dart
> +      ),
Тему приложения всегда лучше выносить в другой файл сразу. Она имеет свойство разрастаться.

2021-06-15 07:42 UTC, saturov commented on lib/ui/auth/auth_page.dart
> +                  if (value!.isEmpty || value.length > 80) {
80 - магическая константа. Вынести в именованную константу

2021-06-15 07:42 UTC, saturov commented on lib/ui/auth/auth_page.dart
> +                },
Это не ок, что валидация происходит на UI. Подумай о том, как можно перенести её в WM.

2021-06-15 07:42 UTC, saturov commented on lib/repository/auth/auth_repository.dart
> +      Logger.d(user.toString());
Не оставляем дебажные логи в репозитории. Если они нужны на постоянку, преобразовать их в i, v или другой тип логов.

2021-06-15 07:42 UTC, saturov commented on lib/repository/auth/auth_repository.dart
> +      return null;
Проглатываешь ошибку. Как ты планируешь с учетом этого обработку ошибок реализовать?

2021-06-15 07:42 UTC, saturov commented on lib/repository/auth/auth_repository.dart
> +      Logger.d(doesAnyUserExist.toString());
Дебажные логи убрать или преобразовать в логи другого типа.

2021-06-15 07:42 UTC, saturov commented on lib/data/auth/data_source/auth_local_data_source.dart
> +    Logger.d('save user: $user');
Дебажные логи

2021-06-15 07:42 UTC, saturov commented on lib/data/auth/data_source/auth_local_data_source.dart
> +  );
Круто, что тут передаешь в конструктор инстанс Hive. Это очень правильный подход.

2021-06-15 07:42 UTC, saturov commented on lib/data/auth/data_source/auth_local_data_source.dart
> +      final box = _hive.box<User>('users');
Эта строка копипастится из функции в функцию. Точно никак нельзя её вынести?

2021-06-15 07:42 UTC, saturov commented on lib/data/auth/data_source/auth_local_data_source.dart
> +  }
Очень много копипасты. Точно можно причесать класс, чтобы её количество снизить.

2021-06-15 10:33 UTC, ivatar39 commented on .gitignore
> +lib/tools
> А почему было решено инструменты не коммитить?

Генератор пришлось переписывать под null-safety и я был очень не уверен местами с null-чеками и правками по линтеру. К тому же, сгенерированный скрин "из коробки" не работал, так как на surf_mwwm используется `ProxyWidgetState`. Пришлось всё равно сгенерированные классы переписывать под чистый mwwm.
Не хотелось всем этим загрязнять репозиторий, скажу честно.

2021-06-15 10:37 UTC, ivatar39 commented on pubspec.yaml
> +  auto_route: 2.2.0
> Почему навигацию было решено делать через это? Каких возможностей в стандартном подходе не хватило?

Авто-раутинг позволил мне динамически менять скрины и их параметры. Не надо писать много бойлерплейта, всё просто решается кодо-генерацией. В будущем возможно будет проще имплементировать дип-линки и раутинг-обсёрверы для аналитики. 
В стандартном подходе не нравится передача аргументов и довольно бойлерплейтный подход к объявлению всех рутов.

2021-06-15 10:42 UTC, ivatar39 commented on pubspec.yaml
> +  hive: ^2.0.4
> Рассматривал ли ты другие варианты для персистентного хранения данных? Почему остановился на этом?

Раньше я использовал SharedPreferences, но потом понял, что хайв делает то же самое, только лучше. Не нужно мануально прописывать toJson и fromJson методы, авто-генерация делает простой адаптер к классу, что сохраняет время и не принуждает к переписыванию служебных методов каждый раз когда дата-класс меняется. Перформанс ещё, но тут я подробно не мониторил. Авторы просто говорят о хороших [результатах](https://raw.githubusercontent.com/hivedb/hive/master/.github/benchmark_write.png).

2021-06-15 10:43 UTC, ivatar39 commented on lib/ui/splash/splash_wm.dart
> +  final AuthRepository _repository;
> Не выразительное имя. Добавится сюда какой-нибудь другой репозиторий, что делать тогда? Трогать код, который не относится к делу?

Не совсем понял конкретно какое имя не устраивает. `SplashWidgetModel` или `AuthRepository`?

2021-06-15 10:48 UTC, ivatar39 commented on lib/ui/router/app_router.dart
> +)
> Расскажи мне про пакет auto_route подробнее. Я им никогда не пользовался. Что он умеет хорошего?

Описал подробнее [выше](https://github.com/ivatar39/board_manager/pull/1#discussion_r651665457)

2021-06-15 10:52 UTC, ivatar39 commented on lib/ui/profile/profile_page.dart
> +        title: const Text('Профиль'),
> На будущее - в любой проект сразу закладывай механизм локализации для строк. Задним числом будет очень сложно интегрировать.

В принципе могу уже сейчас задействовать [библиотеку](https://pub.dev/packages/flappy_translator), которую использую обычно. Много времени не займёт.

2021-06-16 12:34 UTC, saturov approved these changes

2021-06-16 12:36 UTC, merged