SPO-13069: Move all screens to Elementary
ivatar39/board_manager pull request #7
Opened 2022-05-27 11:24 UTC by martynov-alex

2022-06-07 09:11 UTC, ivatar39 requested changes
Пробежался бегло, добавил комменты. Нужно прогнать форматирование и посмотрю ещё раз тогда.

2022-06-07 09:11 UTC, ivatar39 commented on lib/ui/auth/auth_widget_model.dart
> +const kMaxNameLength = 80;
Префикс "k" для констант особо не нужен.

2022-06-07 09:11 UTC, ivatar39 commented on lib/ui/auth/auth_widget_model.dart
> +const kMaxNameLength = 80;
Так как константа локальная, она должна быть приватной.

2022-06-07 09:11 UTC, ivatar39 commented on lib/ui/auth/auth_widget_model.dart
> +      getIt<AppRouter>(),
getIt, как и любой другой DI стараемся не заносить в модельку, для этого создаётся отдельный builder-файл.

2022-06-07 09:11 UTC, ivatar39 commented on lib/ui/catalog/catalog_model.dart
> +  CatalogModel(this._catalogInteractor, this._gameRepository);
Кажется что с форматированием что-то не то. Пробовал
`flutter format lib/ -l 120`?

2022-06-07 09:11 UTC, ivatar39 commented on lib/ui/catalog/catalog_widget.dart
> +        body: EntityStateNotifierBuilder<List<Game>>(
Тут можно было на `Iterable` заменить, но это не так важно

2022-06-07 09:11 UTC, ivatar39 commented on lib/ui/collection/collection_model.dart
> +  AppRouter get router => _router;
Не совсем нравится практика создания геттеров по всем приватным полям. Это обязательно?

2022-06-07 09:11 UTC, ivatar39 commented on lib/ui/collection/collection_widget_model.dart
> +/// Builder for
Точно с форматированием что-то не так.

2022-06-07 09:11 UTC, ivatar39 commented on lib/ui/collection/collection_widget_model.dart
> +CollectionWidgetModel collectionWidgetModelFactory(BuildContext context) {
Точка в конце документации нужна, должно выглядеть так:
/// Builder for [CollectionWidgetModel].

2022-06-07 09:11 UTC, ivatar39 commented on lib/ui/collection/collection_widget_model.dart
> +  void openCatalog();
Неплохо было бы пустыми строками методы разделять.

2022-06-07 09:13 UTC, ivatar39 commented
Самое главное по неймингу - "Move" вряд ли подходящее слово, скорее подошло бы "Migrate" или "Change".
Или "MWWM -> Elementary"

2022-06-07 11:54 UTC, martynov-alex commented on lib/ui/catalog/catalog_model.dart
> +  CatalogModel(this._catalogInteractor, this._gameRepository);
Тут не очень понимаю. Что ты имеешь ввиду? 
У меня в Android Studio в Code Style выставлено 120 символов. Но в этом файле даже нет таких строк.

2022-06-07 12:07 UTC, martynov-alex commented on lib/ui/collection/collection_widget_model.dart
> +  void openCatalog();
Ты имеешь ввиду отделять методы от полей?

2022-06-07 12:20 UTC, martynov-alex commented on lib/ui/collection/collection_model.dart
> +  AppRouter get router => _router;
Не обязательно, но я считал, что это нужно делать по умолчанию. Убрать ненужные?

2022-06-07 12:21 UTC, martynov-alex commented on lib/ui/collection/collection_widget_model.dart
> +/// Builder for
По прежнему не понимаю 😑

2022-06-07 12:22 UTC, martynov-alex commented on lib/ui/collection/collection_widget_model.dart
> +CollectionWidgetModel collectionWidgetModelFactory(BuildContext context) {
Это то, о чем мы говорили. Я не делал документацию, а артефакты заготовок остались.

2022-06-07 12:24 UTC, martynov-alex commented
> Самое главное по неймингу - "Move" вряд ли подходящее слово, скорее подошло бы "Migrate" или "Change".
Или "MWWM -> Elementary"

Я все думал про переезд и почему-то так перевел. Но ты прав, конечно, Migrate более правильный вариант.

2022-06-07 12:51 UTC, martynov-alex commented on lib/ui/auth/auth_widget_model.dart
> +      getIt<AppRouter>(),
Вот тут не очень понял... можешь как-то поподробнее пояснить, что ты имеешь ввиду, где почитать

2022-06-08 12:54 UTC, ivatar39 commented on lib/ui/auth/auth_widget_model.dart
> +      getIt<AppRouter>(),
https://github.com/ivatar39/board_manager/pull/1#discussion_r651501122
Вот так, мы отдельно делаем builder как прослойку между DI и моделью

https://github.com/ivatar39/board_manager/blob/f07ccc3ad5484ff6b75064e62d43338872bbde6b/lib/ui/splash/splash_wm_builder.dart

2022-06-08 12:55 UTC, ivatar39 commented on lib/ui/catalog/catalog_model.dart
> +  CatalogModel(this._catalogInteractor, this._gameRepository);
Странно, кажется это у меня GitHub так линии сворачивает. Если команда не даёт изменений, то тогда всё ок

2022-06-08 12:56 UTC, ivatar39 commented on lib/ui/collection/collection_model.dart
> +  AppRouter get router => _router;
YAGNI - раз не нужно, тогда убирай 😉

2022-06-08 12:56 UTC, ivatar39 commented on lib/ui/collection/collection_widget_model.dart
> +/// Builder for
Должно быть ок, я затупил

2022-06-08 12:56 UTC, ivatar39 commented on lib/ui/collection/collection_widget_model.dart
> +CollectionWidgetModel collectionWidgetModelFactory(BuildContext context) {
Понял, хорошо

2022-06-08 12:57 UTC, ivatar39 commented on lib/ui/collection/collection_widget_model.dart
> +CollectionWidgetModel collectionWidgetModelFactory(BuildContext context) {
Просто это часто такое случается когда в файле дифф отображается и начинаешь думать, что этот человек не просто перенёс контент откуда-то, а сам что-то дописывал, поэтому путанница возникает

2022-06-08 12:58 UTC, ivatar39 commented on lib/ui/collection/collection_widget_model.dart
> +  void openCatalog();
Вот так:
```dart
void onRetryPressed();

void openProfile();

void openCatalog();
```

2022-06-08 12:58 UTC, ivatar39 commented on lib/ui/collection/collection_widget_model.dart
> +  void openCatalog();
Немного вредный совет, но иногда говорят: "код должен дышать". Повышает читаемость

2022-06-08 12:59 UTC, ivatar39 commented
> > Самое главное по неймингу - "Move" вряд ли подходящее слово, скорее подошло бы "Migrate" или "Change".
> > Или "MWWM -> Elementary"
> 
> Я все думал про переезд и почему-то так перевел. Но ты прав, конечно, Migrate более правильный вариант.

Ну PR доступен к изменениям, заголовок поменять можно и наверное нужно

2022-06-08 13:21 UTC, martynov-alex commented on lib/ui/auth/auth_widget_model.dart
> +      getIt<AppRouter>(),
Прости, может, жутко туплю. Но я правильно понимаю, что ты говоришь о том, что надо просто вынести код фабрики WM в отдельный файл? Т.е. на примере сплеша [вот это](https://github.com/ivatar39/board_manager/blob/ea9d120879686e3b13ac5f38882626e19357878b/lib/ui/splash/splash_widget_model.dart#L10)

Т.е. на каждом экране добавится по одному дополнительному файлу с фабрикой

2022-06-08 14:10 UTC, ivatar39 commented on lib/ui/auth/auth_widget_model.dart
> +      getIt<AppRouter>(),
Да, `builder`-метод принимает контекст и возвращает `SplashWidgetModel`

2022-06-08 15:10 UTC, martynov-alex commented on lib/ui/collection/collection_model.dart
> +  AppRouter get router => _router;
В общем, я немного поторопился с ответом. Только в одном месте не используется геттер, убрал его.

2022-06-10 10:57 UTC, ivatar39 requested changes
Пару вещей поправить и ок, но если не хватает времени можешь просто посмотреть

2022-06-10 10:57 UTC, ivatar39 commented on lib/ui/auth/auth_widget_model_builder.dart
> +AuthWidgetModel authWidgetModelFactory(BuildContext context) {
Небольшое замечание по нэймингу.
1. Это не `authWidgetModelFactory`, а `authWidgetModelBuilder`, смотри по названию файла.
2. Метод должен быть глаголом, то есть я бы переименовал в `buildAuthWidgetModel`

2022-06-10 10:57 UTC, ivatar39 commented on lib/ui/catalog/catalog_widget.dart
> +                  final game = games.elementAt(index);
Можешь посмотреть чем `Iterable` от `List` отличается и почему для него не доступна конструкция по типу `"[index]"`, это важная тема

2022-06-10 10:57 UTC, ivatar39 commented on lib/ui/catalog/catalog_widget_model.dart
> +      (event) async {
Можно заменить на `(_)`

2022-06-10 10:57 UTC, ivatar39 commented on lib/ui/catalog/catalog_widget_model_builder.dart
> +CatalogWidgetModel catalogWidgetModelFactory(BuildContext context) {
То же самое как выше

2022-06-10 10:57 UTC, ivatar39 commented on lib/ui/collection/collection_widget_model_builder.dart
> +CollectionWidgetModel collectionWidgetModelFactory(BuildContext context) {
То же самое как выше

2022-06-10 10:57 UTC, ivatar39 commented on lib/ui/profile/profile_widget_model_builder.dart
> +ProfileWidgetModel profileWidgetModelFactory(BuildContext context) {
То же самое как выше

2022-06-10 10:57 UTC, ivatar39 commented on lib/ui/splash/splash_widget_model_builder.dart
> +SplashWidgetModel splashWidgetModelFactory(BuildContext context) {
То же самое как выше

2022-06-11 09:16 UTC, martynov-alex commented on lib/ui/auth/auth_widget_model_builder.dart
> +AuthWidgetModel authWidgetModelFactory(BuildContext context) {
Блин, такие досадные ошибки, нет еще насмотренности. Ты абсолютно прав, правлю.

2022-06-11 09:30 UTC, martynov-alex commented on lib/ui/catalog/catalog_widget.dart
> +                  final game = games.elementAt(index);
Суть примерно такая:  Разница между ними в том, что при работе с Iterable мы обращаемся к списку Iterable каждый раз заново. Тогда как при обращении к List, он единожды создается, помещается в память и мы уже работаем с ним.
Т.е. если нам нужен, например, первый элемент или первые 10 из сотни один раз, то выгоднее работать с Iterable, если нужно постоянно как-то работать с одними и теме же данными, то лучше использовать List.

Пример в гисте https://dartpad.dev/?id=martynov-alex%2F65fb3579305821fb14f0957b53b2fb05

2022-06-14 07:41 UTC, ivatar39 approved these changes
LGTM

2022-06-14 07:49 UTC, merged